name: Cozy Feed Deploy UI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data.json' # Tránh deploy lại UI chỉ vì data.json thay đổi
  workflow_dispatch:      # Kích hoạt thủ công từ tab Actions

permissions:
  contents: write # Cần quyền ghi để push lên nhánh gh-pages

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Static HTML Build
        run: deno task build

      - name: Deploy to GitHub Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
